name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (for future testing)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    # Futuro: Agregar pruebas unitarias aquí
    # - name: Run tests
    #   run: npm test
      
    - name: Deploy to Hostinger via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        # Variables definidas en GitHub Secrets: Settings > Secrets and variables > Actions
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          # Navegar a la carpeta worldx en el hosting
          cd /home/${{ secrets.HOSTINGER_USERNAME }}/public_html/worldx
          
          # Verificar si es un repositorio Git
          if [ -d ".git" ]; then
            echo "Actualizando repositorio existente..."
            git pull origin main
          else
            echo "Inicializando repositorio en la carpeta worldx..."
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git fetch origin
            git checkout -b main origin/main
          fi
          
          echo "Deployment completed successfully!"
          echo "Deployed at: $(date)"
          echo "Location: /home/${{ secrets.HOSTINGER_USERNAME }}/public_html/worldx" 